name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint
        run: bun run lint

      - name: Run type check
        run: bunx tsc --noEmit

      - name: Run tests
        run: bun test

      - name: Build
        run: bun run build

      - name: Verify build outputs
        run: |
          test -f dist/index.js
          test -f dist/index.d.ts